{"name": "test_login_no_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1", "trace": "self = <allure_study.test_feature_story.TestLogin object at 0x1017adfd0>\n\n    @allure.story('密码缺失')\n    def test_login_no_password(self):\n    \n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\nE             +'1'\nE             -1\n\ntest_feature_story.py:42: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1632042731944, "stop": 1632042731944}, {"name": "点击密码", "status": "passed", "start": 1632042731944, "stop": 1632042731944}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1\n", "trace": "  File \"/Users/bytedance/PycharmProjects/allureProject/allure_study/test_feature_story.py\", line 42, in test_login_no_password\n    assert '1' == 1\n"}, "start": 1632042731944, "stop": 1632042731944}], "start": 1632042731943, "stop": 1632042731945, "uuid": "33b24890-7e31-4a36-a11d-b7a666af2d35", "historyId": "c50090ffb7a503d2772ef5d85c666b64", "testCaseId": "f6f413c6d26d10fadefa7601f2b98993", "fullName": "test_feature_story.TestLogin#test_login_no_password", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "FVFC81ZUL414"}, {"name": "thread", "value": "85741-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}